[theme]

# Primary accent for interactive elements

primaryColor = '#3F72AF'

# Background color for the main content area
backgroundColor = '#F9F7F7'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#DBE2EF'

# Color used for almost all text
textColor = '#112D4E'


# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
#font = "sans serif"